2020-01-21T11:58:44.389490+00:00 app[web.1]: [2020-01-21 11:58:44 +0000] [10] [INFO] Booting worker with pid: 10
2020-01-21T11:58:44.454927+00:00 app[web.1]: [2020-01-21 11:58:44 +0000] [11] [INFO] Booting worker with pid: 11
2020-01-21T11:58:44.652647+00:00 app[web.1]: [2020-01-21 11:58:44 +0000] [10] [ERROR] Exception in worker process
2020-01-21T11:58:44.652674+00:00 app[web.1]: Traceback (most recent call last):
2020-01-21T11:58:44.652683+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-01-21T11:58:44.652690+00:00 app[web.1]: worker.init_process()
2020-01-21T11:58:44.652692+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-01-21T11:58:44.652695+00:00 app[web.1]: self.load_wsgi()
2020-01-21T11:58:44.652697+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-01-21T11:58:44.652699+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-01-21T11:58:44.652705+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-01-21T11:58:44.652708+00:00 app[web.1]: self.callable = self.load()
2020-01-21T11:58:44.652710+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-01-21T11:58:44.652712+00:00 app[web.1]: return self.load_wsgiapp()
2020-01-21T11:58:44.652714+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-01-21T11:58:44.652716+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-01-21T11:58:44.652718+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
2020-01-21T11:58:44.652720+00:00 app[web.1]: mod = importlib.import_module(module)
2020-01-21T11:58:44.652722+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-01-21T11:58:44.652729+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-01-21T11:58:44.652736+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2020-01-21T11:58:44.652738+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2020-01-21T11:58:44.652740+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2020-01-21T11:58:44.652742+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2020-01-21T11:58:44.652744+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2020-01-21T11:58:44.652746+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-01-21T11:58:44.652748+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2020-01-21T11:58:44.652750+00:00 app[web.1]: from LeNode import App
2020-01-21T11:58:44.652752+00:00 app[web.1]: File "/app/LeNode/__init__.py", line 2, in <module>
2020-01-21T11:58:44.652754+00:00 app[web.1]: from flask_sqlalchemy import SQLAlchemy
2020-01-21T11:58:44.652763+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask_sqlalchemy'
2020-01-21T11:58:44.652766+00:00 app[web.1]: [2020-01-21 11:58:44 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-01-21T11:58:44.758135+00:00 app[web.1]: [2020-01-21 11:58:44 +0000] [11] [ERROR] Exception in worker process
2020-01-21T11:58:44.758139+00:00 app[web.1]: Traceback (most recent call last):
2020-01-21T11:58:44.758141+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-01-21T11:58:44.758144+00:00 app[web.1]: worker.init_process()
2020-01-21T11:58:44.758146+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-01-21T11:58:44.758148+00:00 app[web.1]: self.load_wsgi()
2020-01-21T11:58:44.758151+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-01-21T11:58:44.758153+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-01-21T11:58:44.758155+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-01-21T11:58:44.758158+00:00 app[web.1]: self.callable = self.load()
2020-01-21T11:58:44.758160+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-01-21T11:58:44.758162+00:00 app[web.1]: return self.load_wsgiapp()
2020-01-21T11:58:44.758164+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-01-21T11:58:44.758166+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-01-21T11:58:44.758168+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
2020-01-21T11:58:44.758171+00:00 app[web.1]: mod = importlib.import_module(module)
2020-01-21T11:58:44.758173+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-01-21T11:58:44.758175+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-01-21T11:58:44.758178+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2020-01-21T11:58:44.758180+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2020-01-21T11:58:44.758182+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2020-01-21T11:58:44.758184+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2020-01-21T11:58:44.758187+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2020-01-21T11:58:44.758189+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-01-21T11:58:44.758191+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2020-01-21T11:58:44.758193+00:00 app[web.1]: from LeNode import App
2020-01-21T11:58:44.758195+00:00 app[web.1]: File "/app/LeNode/__init__.py", line 2, in <module>
2020-01-21T11:58:44.758197+00:00 app[web.1]: from flask_sqlalchemy import SQLAlchemy
2020-01-21T11:58:44.758204+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask_sqlalchemy'
2020-01-21T11:58:44.758895+00:00 app[web.1]: [2020-01-21 11:58:44 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-01-21T11:58:44.816539+00:00 app[web.1]: Traceback (most recent call last):
2020-01-21T11:58:44.816547+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
2020-01-21T11:58:44.817681+00:00 app[web.1]: self.sleep()
2020-01-21T11:58:44.817684+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 357, in sleep
2020-01-21T11:58:44.817686+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2020-01-21T11:58:44.817688+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2020-01-21T11:58:44.817690+00:00 app[web.1]: self.reap_workers()
2020-01-21T11:58:44.817692+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2020-01-21T11:58:44.817998+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2020-01-21T11:58:44.818038+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2020-01-21T11:58:44.818041+00:00 app[web.1]: 
2020-01-21T11:58:44.818043+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-01-21T11:58:44.818045+00:00 app[web.1]: 
2020-01-21T11:58:44.818048+00:00 app[web.1]: Traceback (most recent call last):
2020-01-21T11:58:44.819606+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2020-01-21T11:58:44.819609+00:00 app[web.1]: sys.exit(run())
2020-01-21T11:58:44.819611+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
2020-01-21T11:58:44.819613+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2020-01-21T11:58:44.819615+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
2020-01-21T11:58:44.819617+00:00 app[web.1]: super().run()
2020-01-21T11:58:44.819619+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
2020-01-21T11:58:44.819621+00:00 app[web.1]: Arbiter(self).run()
2020-01-21T11:58:44.819624+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 229, in run
2020-01-21T11:58:44.819626+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2020-01-21T11:58:44.819628+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 342, in halt
2020-01-21T11:58:44.819630+00:00 app[web.1]: self.stop()
2020-01-21T11:58:44.819653+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
2020-01-21T11:58:44.819966+00:00 app[web.1]: time.sleep(0.1)
2020-01-21T11:58:44.819971+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2020-01-21T11:58:44.821078+00:00 app[web.1]: self.reap_workers()
2020-01-21T11:58:44.821081+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2020-01-21T11:58:44.821084+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2020-01-21T11:58:44.821086+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2020-01-21T11:58:44.907791+00:00 heroku[web.1]: Process exited with status 1
2020-01-21T11:58:44.934445+00:00 heroku[web.1]: State changed from starting to crashed
2020-01-21T11:59:10.412988+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=lenode.herokuapp.com request_id=416dfacc-156c-4640-83dd-f6a16088a798 fwd="197.221.251.12" dyno= connect= service= status=503 bytes= protocol=https
2020-01-21T11:59:18.661355+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=lenode.herokuapp.com request_id=a149daea-3c06-4fe5-96a6-4d325d4b81f7 fwd="197.221.251.12" dyno= connect= service= status=503 bytes= protocol=https
2020-01-21T12:01:20.833650+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=lenode.herokuapp.com request_id=ce4d89fa-76e4-4bde-9980-7f0e0a5dd285 fwd="197.221.251.12" dyno= connect= service= status=503 bytes= protocol=https
2020-01-21T12:01:29.777770+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=lenode.herokuapp.com request_id=581e42ec-1436-467b-812f-ae94a371e8ee fwd="197.221.251.12" dyno= connect= service= status=503 bytes= protocol=https
Terminate batch job (Y/N)? Terminate batch job (Y/N)? 